apiVersion: v1
kind: Secret
metadata:
  name: pxc-secret
type: Opaque
data:
  root_password: **********
  discovery_service: 10.20.2.4:2379
  cluster_name: k8scluster2
  xtrabackup_passwod: **********
  mysql_proxy_user: proxyuser
  mysql_proxy_password: **********
